# Generated by Django 4.1.5 on 2023-01-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blinguser',
            name='dashboard_user',
            field=models.CharField(max_length=65, null=True, unique=True),
        ),
    ]
