# Generated by Django 4.1.5 on 2023-01-15 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_blinguser_dashboard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blinguser',
            name='dashboard_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
