# Generated by Django 4.1.5 on 2023-01-15 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_blinguser_dashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='bling_user',
            field=models.CharField(max_length=65, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blinguser',
            name='api_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.apidata'),
        ),
    ]
