# Generated by Django 4.1.5 on 2023-01-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_blinguser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='bling_user',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
