# Generated by Django 4.1.5 on 2023-01-17 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_alter_apidata_bling_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blinguser',
            name='api_data',
        ),
        migrations.AddField(
            model_name='apidata',
            name='api_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.blinguser'),
        ),
        migrations.AlterField(
            model_name='blinguser',
            name='dashboard_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
