# Generated by Django 4.1.5 on 2023-01-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_blinguser_api_data_apidata_api_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='api_data',
        ),
        migrations.AlterField(
            model_name='apidata',
            name='bling_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.blinguser'),
        ),
    ]
