# Generated by Django 4.1.5 on 2023-01-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_apidata_bling_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apidata',
            name='bling_user',
        ),
        migrations.AddField(
            model_name='blinguser',
            name='api_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.apidata'),
        ),
    ]
